version: "3"
services:
  app:
    build: .
    container_name: app
    ports:
      - ${PORT}:${PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}      
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - diary_api
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - ${DB_PORT}:${DB_PORT_DOCKER}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}      
    volumes:
      - db-diary-api:/var/lib/postgresql/data
    networks:
      - diary_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-diary-api:
networks:
  diary_api:
    driver: bridge
